language: python
python:
  - "3.3"
# command to install dependencies
before_install:
  - "sudo apt-get install python3-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl1.2-dev libsmpeg-dev python-numpy libportmidi-dev ffmpeg libswscale-dev libavformat-dev libavcodec-dev checkinstall mercurial"
  - "hg clone https://bitbucket.org/pygame/pygame"
  - "cd pygame"
  - "python3 setup.py build"
  - "sudo checkinstall python3 setup.py install"
  - "cd .."
install:
  - "pip install -r requirements.txt"
  - "python setup.py install"    
# command to run tests
script: images -h
notifications:
  email: false
